apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deployment
  labels:
    app: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: 4oh4/jenkins-docker
        ports:
        - containerPort: 8080
        - containerPort: 50000
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: "jenkins-volume"
          readOnly: false
      volumes:
      - hostPath:
          path: "/var/run/docker.sock"
        name: "jenkins-volume"
