apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deployment
  labels:
    app: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      securityContext:
        fsGroup: 117
      containers:
      - name: jenkins
        image: alok1996saxena/docker-jenkins
        ports:
        - containerPort: 8080
        - containerPort: 50000
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: "jenkins-volume"
          readOnly: false
      volumes:
      - hostPath:
          path: "/var/run/docker.sock"
        name: "jenkins-volume"
        
***************************************************************************************

apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/run/docker.sock"


********************************************************************************************

